FROM python:3.10-slim-bullseye

WORKDIR /app
COPY . /app

RUN apt-get update && apt-get install -y gcc python3-dev
RUN pip install --trusted-host pypi.python.org -r requirements.txt
RUN mkdir -p /logs && chmod 777 /logs

EXPOSE 8000

CMD ["gunicorn", "backend.app:app", "-c", "gunicorn_config.py"]
