FROM python:3.10-slim-bullseye

WORKDIR /app

COPY . /app

RUN apt-get update && apt-get install -y gcc python3-dev
RUN pip install --trusted-host pypi.python.org -r requirements.txt

EXPOSE 8501
ENV PYTHONPATH="${PYTHONPATH}:/app"

CMD ["streamlit", "run", "src/main.py"]
