FROM python:3.10-slim-bullseye

WORKDIR /app
COPY . /app

RUN apt-get update && apt-get install -y gcc python3-dev
RUN pip install --trusted-host pypi.python.org -r requirements.txt
EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
